### ISSUE TITLE
Failure to list all resource traits in resource details

### ISSUE THREAD

**Issue by ddossot** [mulesoft/api-console#121]
Currently the resource type is shown next to its path. It would be great to also list all the traits applied to this resource. Since it can be a lot, showing this list in the expanded detailed view would be good enough.

**Comment by jcenturion** [comment]
We are currently listing traits on details view.

![screen shot 2015-03-10 at 12 14 54 pm](https://cloud.githubusercontent.com/assets/302314/6583185/aad17d0c-c71f-11e4-8f8c-c056dbf2864c.png)

**Comment by ddossot** [comment]
I've just upgraded my console but I still don't see traits:

![screenshot from 2015-03-10 14 10 50](https://cloud.githubusercontent.com/assets/119028/6585462/5c0a9d88-c72f-11e4-8eca-b5d1c8e688e4.png)

Here is the definition of my sub-resource:

```yaml
    /pages:
      is: [legacyPages, subCollection]
      type: pagedCollection
```

For the record, the `pagedCollection` type also has traits:

```yaml
  - pagedCollection:
      get:
        is: [versioned, paged, countable, sortable_by_creation_date]
```

**Comment by jcenturion** [comment]
@ddossot: it seems to be that for some cases the console is not showing traits. We will tackle this bug soon.

Using the following RAML, I've found:

```yaml
traits:
  - historical:
      queryParameters:
        since:
          type: string
  - filterable:
      queryParameters:
        filter:
          type: string
  - searchable:
      queryParameters:
        offset:

resourceTypes:
  - pagedCollection:
      get:
        # not shown
        is: [searchable]

/pages:
  # not shown
  is: [historical]
  type: pagedCollection

  post:
    # works
    is: [filterable]
```

- The console is not showing resource level traits (historical)

![screen shot 2015-03-10 at 3 20 42 pm](https://cloud.githubusercontent.com/assets/302314/6586772/9436eb62-c739-11e4-910b-125ba319f892.png)

- The console is not showing traits inherited from resourceTypes (searchable)

![screen shot 2015-03-10 at 3 21 07 pm](https://cloud.githubusercontent.com/assets/302314/6586773/972c353e-c739-11e4-8ca5-842b7909f937.png)

- The console is showing method level traits. However, it's not showing the ones inherited from the parent level (historical).

![screen shot 2015-03-10 at 3 23 29 pm](https://cloud.githubusercontent.com/assets/302314/6586774/996e2514-c739-11e4-9644-aecdc5bdad92.png)

**Comment by jcenturion** [comment]
@ddossot: The following RAML is now working ;). But, I've found there is a bug on the RAML parser:

- Traits declare at resourceType are not loaded into traits list. For example:

```yaml
resourceTypes:
  - pagedCollection:
      get:
        is: [searchable]
```
You will never saw searchable listed. Fortunately, the trait is been applied to the resource, only the list of traits is incorrect. I will log a bug on the raml-parser.

```yaml
traits:
  - historical:
      queryParameters:
        since:
          type: string
  - filterable:
      queryParameters:
        filter:
          type: string
  - searchable:
      queryParameters:
        offset:

resourceTypes:
  - pagedCollection:
      get:
        is: [searchable]

/pages:
  is: [historical]
  type: pagedCollection

  post:
    is: [filterable]
```

![screen shot 2015-03-11 at 11 11 03 am](https://cloud.githubusercontent.com/assets/302314/6603531/0dacd6e0-c7e0-11e4-8a12-9b8aa368fcc9.png)

![screen shot 2015-03-11 at 11 11 21 am](https://cloud.githubusercontent.com/assets/302314/6603533/0dae1eec-c7e0-11e4-925c-708eced20b7f.png)

![screen shot 2015-03-11 at 11 11 12 am](https://cloud.githubusercontent.com/assets/302314/6603532/0dadf7b4-c7e0-11e4-8323-174339636d25.png)
