### ISSUE TITLE
Drop-down of optional query params should have an empty selection and clear to empty

### ISSUE THREAD

**Issue by ddossot** [mulesoft/api-console#125]
With the following query parameter:

```yaml
      role:
        description: Restricts the scope of the returned pages.
        example: author
        type: string
        enum: [ viewer, author ]
        required: false
```
The console shows this:

![screenshot from 2015-03-13 11 40 31](https://cloud.githubusercontent.com/assets/119028/6645016/ef44a4c0-c975-11e4-9150-482f85d94936.png)

If I want no value, which is legal, I have to override and manually delete the value.

If think it would be more correct to:

- have a third empty entry in the drop down,
- have the Clear button remove all example values (as it does currently) and use an empty value for such optional drop down.
