### ISSUE TITLE
binary/octet-stream in PUT renders text area, should it be a file-selection control?

### ISSUE THREAD

**Issue by rtang-atlassian** [mulesoft/api-console#130]
Hi,

```
put:
  description:
  body:
    binary/octet-stream:
```

In 'Try it', the binary/octet-stream selection shows a text area control. I'm expecting a file selection control  so I can PUT with a file, not just strings.

Cheers
Raymond
