### ISSUE TITLE
Override baseUriParameters is not working

### ISSUE THREAD

**Issue by shravanak** [mulesoft/api-console#136]
I have a baseURIparameter I want to override for one of the api but that doesnt seem to take into effect.

``` yaml
title: API Documentation
baseUri: http://{apiDomain}:4080/analytics/{ver}
baseUriParameters:
  ver:
    description: |
      The version of the API
    enum: ["v1"]
  apiDomain:
    description: |
      The version of the API
    enum: ["validurlishere"]

/resource:
/aggregate/contents:
  baseUriParameters:
    ver:
      enum: ["v2"]
  get:
    description: |
      Returns metrics
```

So in this case I want the "ver" to be v2 but it is still v1

**Comment by scranen** [comment]
I'm in a similar situation. We have a different prefix for private parts of the API than for the public parts:
```yaml
#%RAML 0.8
baseUri: http://my.domain/{api_type}/{version}
baseUriParameters:
  api_type: { enum: [ "public", "private" ] }
```
What I would like to do:
```yaml
resourceTypes:
  - private:
      uriParameters:
        api_type: { enum: [ "private" ] }
  - public:
      uriParameters:
        api_type: { enum: [ "public" ] }

...

/my/resource:
  type: private
```
Desired effect: the API console prefills the `api_type` URI parameter with the single allowed value. Currently, the `uriParameters` property in the resource type is ignored.

It is not clear from the RAML 0.8 spec whether `baseUriParameters` should be used (see the 2nd example in section _Base URI and baseUriParameters_) to declare the `api_type` parameter, or `uriParameters` (see the 2nd example in section _URI Parameters_). As it stands, `uriParameter` is not accepted by the API console as a top-level property, even though it is accepted by the API workbench.
