### ISSUE TITLE
Support for character categories as regex pattern for parameters.

### ISSUE THREAD

**Issue by monami555** [mulesoft/api-console#143]
Is it planned to introduce support for character categories as part of the regex for API parameters? For example such RAML definition:

```
 /foo/{bar}:
    uriParameters:
      bar:
        type: string
        pattern: "\\p{L}+"
     get:
```

cannot be easily used in API Console as any input in the "bar" field is considered invalid. I assume this is because JavaScript does not support the \p{...} scripts out of the box. Would it be possible to add such functionality to API Console, or is it completely out of scope?
