### ISSUE TITLE
Console does not perform requests when there is a non-standard auth method

### ISSUE THREAD

**Issue by mmatloka** [mulesoft/api-console#145]
Our raml have a very basic auth included in `securedBy` :

```
- api_key:
    type: x-basic-key
    description: Token in "Authorization" header, value "Bearer <token>". Token defined in application configueration.
```

According to https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#type-1 such config is allowed. When I click e.g. a `GET` button, request to the backend is not performed. In raml console the 'spinning' circle and cancel button appears, but never ends. When I have deleted the `securedBy` suddenly the `GET` works.

**Comment by agines** [comment]
Had the same issue, it seems that this will only work if you set the security type as "x-custom". If you set anything else, it won't work.

**Comment by mmatloka** [comment]
@agines thx! `x-custom` works!

**Comment by sichvoge** [comment]
@mmatloka anything else or can I close the issue?

**Comment by mmatloka** [comment]
Hi @sichvoge ,
I would say its a bug that `x-custom` is the only allowed value for the `api-console`. According to the spec https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#type-1 it can be `x-{anything}`.

**Comment by sichvoge** [comment]
Wonder why that is not working as I have one described as the following:

```
description: "The access token provided by the authentication application"
type: x-access_token
describedBy:
  headers:
    Authorization:
      description: "Used to validate a OAuth 2 access token."
      example: AABBCCDD
      required: true
      type: string
```

No problems inside the console as well.
