### ISSUE TITLE
x-Something Security Scheme not recognized int Try-it

### ISSUE THREAD

**Issue by mgsnova** [mulesoft/api-console#149]
When using a custom security scheme, at least the configured Header is not listed in the Headers when using "Try it".
Also when adding the Header by hand and starting the request, there is no real request being made.

Example RAML file:
```
#%RAML 0.8
---
title: Test
protocols: [ HTTP ]

securitySchemes:
  - apiToken:
      type: x-API-Token
      describedBy:
        headers:
          API-Token:
             type: string

securedBy: [apiToken]

/test:
  get:
```
