### ISSUE TITLE
repeatable headers are not allowed to be empty

### ISSUE THREAD

**Issue by monami555** [mulesoft/api-console#151]
As soon as I mark a header as repeatable, but not required, the API Console still marks the related input field as invalid if the value is empty (I have to enter some text and then delete it in order to trigger the invalidation):

![repeat_header](https://cloud.githubusercontent.com/assets/1808940/8501073/6215b730-21a2-11e5-9c9c-61c5b74fbd0f.png)

Related RAML:

```
#%RAML 0.8
title: bla
baseUri: http://localhost/
version: v1
mediaType:  application/json

/foo:
  get:
    headers:
      bla:
         type: string
         required: false
         repeat: true
```

It may be partially related to #138 and #81, but has a smaller scope, so maybe could be tackled in the meantime?
