### ISSUE TITLE
yaml anchor replacements

### ISSUE THREAD

**Issue by reesew** [mulesoft/api-console#171]
I don't know if this is an issue with api-console, or the raml spec, but I can't use yaml's ability to extend objects defined earlier, I get an error about only allowing scalar keys. Here's an example:

```yaml
extendable: &extendable
  inherited: prop
extended:
  <<: *extendtable
  extra: prop0
items:
  - <<: *extendable
    extra: prop1
  - <<: *extendable
    extra: prop2
```
which should expand to 
```yaml
...
extended:
  inherited: prop
  extra: prop0
items:
  - inherited: prop
    extra: prop1
  - inherited: prop
    extra: prop2
```
