### ISSUE TITLE
Missing button "browse" a file in raml language?

### ISSUE THREAD

**Issue by tnguyen390** [mulesoft/api-console#173]
I want to browse a file in RAML like the tool postman, but when I write in RAML language is not support for that. And It doesn't have button "Browse", so I don't know how to attach a file to endpoint.

**Comment by ddossot** [comment]
Context: see [this SO question](http://stackoverflow.com/questions/32220405/how-to-browse-a-file-in-raml-language).

Basically, the API Console needs to support fields of type `file` in this kind of RAML spec:
```yaml
body:
  multipart/form-data:
    formParameters:
      file:
        description: The file to be uploaded
        required: true
        type: file
```
