### ISSUE TITLE
No feedback for file type

### ISSUE THREAD

**Issue by JaniszM** [mulesoft/api-console#199]
It seems that api-console (and as well api-designer ;) ) has no feedback for file type:

```
put: 
    description: Puts an image file.
    body: 
        multipart/form-data: 
            formParameters:
                image:
                    description: The image file.
                    type: file
                    required: true
```

This should be done probably by html type="file", then we have nice popup of file browser: http://www.w3schools.com/tags/att_input_type.asp.
