### ISSUE TITLE
Bug: Can't set default value for enum. 

### ISSUE THREAD

**Issue by JaniszM** [mulesoft/api-console#204]
Like in subject, seems we cannot set default value for enum :( First one from the list is always taken or none if enum field is not required.

Can you guys check this out?

**Comment by sichvoge** [comment]
Guess that's in the TryIt. It's true that the console does not automatically set the value to the default when using an enum. For example:

```yaml
#%RAML 0.8
title: My REST API
version: v1
baseUri: /api/{version}

/endpoint:
  get:
    description: List currently tracked ecosystems, always sorted by name alphabetically
    headers:
      custom:
        type: string
        enum: [ "api", "rest" ]
        default: api
```

I get the following:

![image](https://cloud.githubusercontent.com/assets/498114/17214537/529495e8-54d1-11e6-96a5-8057f121d6b5.png)

The dropdown should be set to "api" by default.
