### ISSUE TITLE
Repeatable headers

### ISSUE THREAD

**Issue by Biribu** [mulesoft/api-console#227]
I want to include a repeteable header in my resource.

Now I am working over an example I created:

This is the result and the red lines mean what I want to achieve if possible:
![repeatable](https://cloud.githubusercontent.com/assets/1679476/13351378/897f755a-dc86-11e5-89f4-456f6d90114a.PNG)

I want the user could create multiple "bla" fields with a "+" button and remove them with a "X" button. Is it possible?

This is my raml code for this example:

```yaml
#%RAML 0.8

title: bla
baseUri: http://localhost/
version: v1
mediaType: application/json

/foo:
  get:
    headers:
      bla:
        type: string
        required: false
        repeat: true
        description: description
```

**Comment by sichvoge** [comment]
Same for RAML 1.0

```yaml
#%RAML 1.0

title: bla
baseUri: http://localhost/
version: v1
mediaType: application/json

/foo:
  get:
    headers:
      bla:
        type: array
        items: string
        required: false
        description: description
```
