### ISSUE TITLE
Set baseUriParameters default values appropriate text inputs

### ISSUE THREAD

**Issue by alvassin** [mulesoft/api-console#269]
E.g. we deploy our api at different servers. I need to have ability to set custom host & port. So, I will make following RAML:

``` yaml
#%RAML 0.8
title: Example API
version: v1
baseUri: https://{host}:{port}
baseUriParameters:
  host:
    displayName: Domain name / ip address
    type: string
    default: localhost
  port:
    displayName: Port
    type: integer
    default: 80
```

After i load it in api console, i will see default value for baseUriParameters, but as text. I wish they would be set in input fields.
