### ISSUE TITLE
Seeing "Invalid type" for custom types in query string params

### ISSUE THREAD

**Issue by marshall007** [mulesoft/api-console#270]
```
#%RAML 1.0
title: test-api
mediaType: application/json
baseUri: ...

types:
  code:
    type: string
    pattern: ^[A-Z\-]+$
    minLength: 3
    maxLength: 50

/contracts:
  get:
    queryParameters:
      lab_code: code
      institutution_code: code
      active: boolean
```

<img width="439" alt="screen shot 2016-04-15 at 6 28 01 pm" src="https://cloud.githubusercontent.com/assets/877936/14577327/1afe26ca-0338-11e6-91ac-f13578633ee3.png">

Validation appears to work correctly if I switch to using inline type declarations:

```
/contracts:
  get:
    queryParameters:
      lab_code:
        type: string
        pattern: ^[A-Z\-]+$
        minLength: 3
        maxLength: 50
```
