### ISSUE TITLE
AnyPoint portal baseUri template issue

### ISSUE THREAD

**Issue by WAvdBeek** [mulesoft/api-console#274]
Overriding a baseUri template value as described in the RAML 0.8 documentation does not work in the AnyPoint portal. The following paragraph and example are taken from the 0.8 documentation.

https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md

In a resource structure of resources and nested resources with their methods, the most specific baseUriParameter fully overrides any baseUriParameter definition made before. In the following example the resource /user/{userId}/imageoverrides the definition made in /users.

``` yaml
#%RAML 0.8
title: Users API
version: 1
baseUri: https://{apiDomain}.someapi.com
/users:
  displayName: retrieve all users
  baseUriParameters:
    apiDomain:
      enum: [ "api" ]
  /{userId}/image:
    displayName: access users pictures
    baseUriParameters:
      apiDomain:
        enum: [ "static" ]
```

The RAML validates correctly and uploads without error. However, in the portal, the value is never set.
Adding a baseUriParameters: apiDomain: enum: [] just after the baseUri itself will create a drop down list of all the values in that enum, but even setting an example: or default: on the actual resource does not select the correct value in the portal.

Adding an enum: at the top just after the baseUri and then selecting a default: in the resources makes much more sense to me, but I would be happy if the documented way actually worked.
