### ISSUE TITLE
Empty documentation: getDocumentationContent splits text using \n - doesn't work if RAML contains Carrige Return, CR + LF

### ISSUE THREAD

**Issue by denis-kalinin** [mulesoft/api-console#294]
The error is in the directive RAML.Directives.rootDocumentation in root-documentation.js
Consider the following code containing CR+LF (`\r\n`) at the end of lines:

``` yaml
#%RAML 0.8

---
title: Cool REST API
baseUri: http://example.com/api
version: v1
documentation:
  - title: Getting started
    content: |
      # Welcome to our cool API
      With our API you can cast magic!
```

If the string in `content` node is `# Welcome to our cool API\r\n`, i.e. formatted **in Windows**, then function `getDocumentationContent()` splitting `content` node to lines will get the first line as: 

``` javascript
var lines = ["#Welcome to our cool API\r", "", "With our API you can cast magic!"];
// \r is invisible in debugger, and it seems strange why getting "identical" string in array with indexOf() fails
```

after splitting the `content` node in function `getDocumentationContent()`. At the same time the function `getMarkdownHeaders()` keeps the same string in headers as

``` javascript
// we get header from content as: var headers = content.match(/^#+\s(.*)$/gim);
var selected = "#Welcome to our cool API";
// there is no \r at the end.
```

then in `getDocumentationContent` we try to match these string with:

``` javascript
var index = lines.indexOf(selected);
//and we get index=-1 because of invisible \r at the end of lines[0]
```

I think this is the reason.
