### ISSUE TITLE
Mocking service should generate example responses from type examples

### ISSUE THREAD

**Issue by Gregroam** [mulesoft/api-console#302]
api.raml

```
#%RAML 1.0
title: Test
version: v1
baseUri: https://mocksvc.mulesoft.com/mocks/foobar

uses:
  tables: ./tables.raml

/foo:
  get:
    responses:
      200:
        body:
          application/json:
            type: tables.Identity
            properties:
              profile: tables.Profile

```

tables.raml

```
#%RAML 1.0 Library

types:

  Identity:
    properties:
      id:
        type: number
        example: 1
      email:
        pattern: "^[A-Za-z]+@[A-Za-z]+\\.[a-z]+$"
        example: John@Smith.com

  Profile:
    properties:
      id:
        type: number
        example: 1
      firstName:
        type: string
        example: John
      lastName:
        type: string
        example: Smith
      identityId:
        type: number
        example: 1

```

In the case of GET /foo, it returns a json response of an Identity model, with the Profile model nested on it under the key "profile".

Example:

```
{
    "id": 1,
    "email": "John@Smith.com",
    "profile": {
        "id": 1,
        "firstName": "John",
        "lastName": "Smith",
        "identityId": 1
    }
}
```

It would be great if the mocking service could generate the example response as I have defined examples for each property on the types used in the response.  This would be useful when you have an api that can return different combinations of database models nested together, and you don't want to have to manually create example responses for each api. Because later if you were to change a database model, you would have to manually edit all your api response examples that use this model, and this is very tedious and counter productive to maintaining the raml spec. 

I would expect that if each property has an example defined, then the mocking service should be able to generate an example response itself. In the case where an array is used, it could just create a one item array perhaps?
