### ISSUE TITLE
!include and absolute URLS

### ISSUE THREAD

**Issue by s0undt3ch** [mulesoft/api-console#304]
I'm trying out api-console and while trying to defer loading of examples and schemas through the use of `!include` I found that when I defined an absolute URL(without the domain part), that absolute URL is just appended to the url from where the api console is served.

Consider:

```
/foo:
  body:
    application/json:
      schema: !include /foo.schema
```

I serve my api-console on `/api` and the request that is made against my server is to `/api/foo.schema`, using both the latest stable and the latest master branch.
When I noticed this, I tried specifying a relative URL to see if that worked, so I updated my RAML file to be:

```
/foo:
  body:
    application/json:
      schema: !include ../foo.schema
```

Using latest stable, the request is still done to `/api/foo.schema` but using the latest master the request is properly done to `/foo.schema`.

Although the master branch does handle this relative URL approach, I still feel that if I provide an absolute URL by starting it with `/` that should be the url to use to get the include contents, ie, I consider the url appending that api-console does to be a bug or an undesirable behaviour.

Would you agree?
