### ISSUE TITLE
still show parameter in the URI when parameter is optional

### ISSUE THREAD

**Issue by davisskchan** [mulesoft/api-console#335]
Resource definition

```
/accounts:
  type: {eeResource.EntityResource: {entity: walletAccountEntity}}
  is: [eeTraits.ee-api]

  get:
    displayName: Get all the accounts within a wallet.
    description: This API method allows the calling application to retrive all accounts for a specific wallet.
    queryParameters:
      status:
        type: string[]
        required: false
        description: Query string for Result filtering by Account Status(es). For single value filtering square brackets could be omitted.
```

Try 2 scenario, it still shows the parameter in the URI

Also the response doesn't show any error.

![scenario1](https://cloud.githubusercontent.com/assets/18424321/18589596/6c6bc3ac-7bf9-11e6-82bb-ada9b097dd12.jpg)
![scenario2](https://cloud.githubusercontent.com/assets/18424321/18589595/6c66f462-7bf9-11e6-881e-cb61e92b30f4.jpg)
