### ISSUE TITLE
parematers examples are not shown when defined in a response

### ISSUE THREAD

**Issue by pokraev** [mulesoft/api-console#339]
Example fragment: responses: 

``` yaml
      201:
        headers:
          location:
            description: The location of the newly created resource
            type: string
            example: /sales-transactions/123
```

![image](https://cloud.githubusercontent.com/assets/8824324/18993627/109313fe-871c-11e6-8121-8f6981091dc3.png)
