### ISSUE TITLE
Is there a way to force API Console to render a "password" input type

### ISSUE THREAD

**Issue by monami555** [mulesoft/api-console#349]
Hello

Down to the point:) Take a look here: http://www.w3schools.com/TAGS/att_input_type.asp at the "password" type description:

> password    -  Defines a password field (characters are masked)

Is there any way to tell API Console that a field should be rendered as input of type "password" ? For example in this snippet:

```
/bla:
  post:
    body:
      application/x-www-form-urlencoded:
        formParameters:
          password:
            required: false
            type: string
            displayName: password
```

We need a way to mask the password field. 

I could not find any property present in RAML specification that would say that the parameter should be of type "password". Are you maybe aware of any workaround to make it appear masked in API Console? Do you see a way of implementing it?

For us it is currently a security issue. I wonder if others stumbled upon similar issues.

Regards,
Monika Machunik

**Comment by monami555** [comment]
In other words, we need a mechanism to be able to mark an arbitrary field in RAML as "sensitive", so that it will be rendered masked in API Console.

Since there is no such keyword in RAML, do you see any possibility of adding such feature in API Console? For example someone could add a configuration to their API Console instance, where they would specify a naming convention for sensitive fields.

Do you maybe have similar configuration mechanism for any other features where we could have a look at, and perhaps try to extend it?

**Comment by sichvoge** [comment]
MH; maybe in the future we can introduce some annotations that are specific for rendering fields, something like:

```
/bla:
  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          password:
            (field.type): password
            required: false
            type: string
            displayName: password
```

Just an idea though! :) We can leave that issue open and discuss ideas.
