### ISSUE TITLE
Required header for security scheme does not render an entry box

### ISSUE THREAD

**Issue by memelet** [mulesoft/api-console#372]
I have a security scheme defined

```
securedBy: [vi_auth]
securitySchemes:
  vi_auth:
    type: x-vi-auth
    description:
      Vimana aquired OAUTH2 JWT
    describedBy:
      headers:
        Authorization:
          type: string
          description: The JWT token, eg 'bearer ad4839cf-3adfafz-JJDND'
          required: true

/auth:
  /admin:
    /users:
      get:
        (permissions): users:read
```

The security info is rendered as part of the users.GET which has text about the required Authorization header. But no entry field for the header.

Only if I add an explicit headers section is there a way to enter the Authorization header:

```
/auth:
  /admin:
    /users:
      get:
        (permissions): users:read
        headers:
          Authorization:
```

Besides having to duplicate the header definition in the raml, the header documentation gets duplicated in the console. 

Maybe related: When I run this using osprey, osprey does not seem to require headers defined in the security scheme. So maybe this is a parser problem?
