### ISSUE TITLE
How to enter application/x-www-form-urlencoded for a post body?

### ISSUE THREAD

**Issue by memelet** [mulesoft/api-console#374]
When the post body is defined as application/x-www-form-urlencoded with a type defining the structure, the UI shows only a dropdown for BODY with the single selection of 'application/x-www-form-urlencoded'. But no way to actually enter the form values.

```
types:
  TokenRequest:
    type: object
    properties:
      username:
        type: string
        required: true
      password:
        type: string
        required: true
      client_id:
        type: string
        required: true
      client_secret:
        type: string
        required: true
      grant_type:
        enum: [password]
        default: password
        required: true

post:
  body:
    application/x-www-form-urlencoded:
    type: TokenRequest
```
