### ISSUE TITLE
Examples for types do not work

### ISSUE THREAD

**Issue by tfayruzov** [mulesoft/api-console#387]
I expect that examples for `types` defined in RAML spec will be rendered in the console, but they are not.

```
#%RAML 1.0
title: Example test
types:
  SimpleType:
    type: string
    examples:
      simple: simple string
      complex: complex string

```
This is what currently renders:
<img width="265" alt="screen shot 2017-01-04 at 5 04 49 pm" src="https://cloud.githubusercontent.com/assets/19192836/21665268/69e32b86-d2a0-11e6-8284-afbb53f6b253.png">
