### ISSUE TITLE
Example facet is not fully supported 

### ISSUE THREAD

**Issue by tfayruzov** [mulesoft/api-console#389]
[Single example](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#single-example) definition describes additional fields that can be set for an example, but those currently do not render in the console.

Repro RAML:
```
#%RAML 1.0
title: Example
version: v1
types:
  SimpleString:
    description: Description of a string type
    type: string
    example:
      displayName: Display name of a string example
      description: Description of a string example
      value: example string
/exampleRes:
  post:
    body:
      application/json:
        type: SimpleString
```

**Comment by nmarinel01** [comment]
Hi @tfayruzov !
If you change "example" by "examples" all examples will be displayed at console. 
Hope this helps.
Regards
![image](https://cloud.githubusercontent.com/assets/19980188/21728721/773b2af4-d426-11e6-8f1e-156e67bbc3d8.png)

**Comment by tfayruzov** [comment]
Thanks for looking into it. If I change example to `examples` it will treat `displayName`, `description` and `value` as separate examples, but that is not what I need. These are the fields that should describe a *single example*. Providing the spec link again: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#single-example. The table with facets there explains that each example can have it's own name and description, not only the example itself. I.e. I can have multiple examples, each with its own description, like:

```
types:
  SimpleString:
    description: Description of a string type
    type: string
    examples:
      example1:
        displayName: Display name of a string example
        description: Description of a string example
        value: example string
      example2:
        displayName: Display name of a string example
        description: Description of a string example
        value: example string
```

Hope that makes my question clearer, please let me know if you need a better elaboration.
