### ISSUE TITLE
Not able to use custom security schemes in api-console v3.0.13

### ISSUE THREAD

**Issue by smparekh** [mulesoft/api-console#395]
Prior issue: #79 says this was fixed but I am still seeing this issue in v3.0.13 of api-console:
![issue](https://cloud.githubusercontent.com/assets/2242057/22521652/b070ae92-e886-11e6-9c71-f378196fde91.png)
using RAML 0.8 spec:
```
securedBy: [ api_key ]
securitySchemes:
  - api_key:
      description: |
        Authorize against the API using provided API Key
      type: x-Authorization
      describedBy:
        headers:
          Authorization:
            example: a1b2c3d4
```
