### ISSUE TITLE
TryIt: Console Response always in delete response body

### ISSUE THREAD

**Issue by llgcode** [mulesoft/api-console#41]
When I use the console to 'get' a resource the response is displayed into the delete tab
```
#%RAML 0.8
---
title: ANY API
version: 1
baseUri: /api
/resource/{resourceId}:
  get:
    description: Get the content of a resource.
  post:
    description: Create a resource.
  delete:
    description: Delete a resource.
```
