### ISSUE TITLE
Render dropdown list for possible enum values.

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#412]
Currently, the console does not render a dropdown list for possible values defined in an enum inside the TryIt view. It would be nice to introduce it to minimize failures putting in values.

An example:

```yaml
types:
  Feature:
    type: string
    enum:
        - A
        - B
        - C

/{user}/{feature}:
  uriParameters:
    feature:
      type: Feature
```

I should get a dropdown list where I can choose "A", "B", or "C".
