### ISSUE TITLE
Accept Header Enum Not usable

### ISSUE THREAD

**Issue by llgcode** [mulesoft/api-console#42]
Enum not usable on Headers
```
#%RAML 0.8
---
title: ANY API
version: 1
baseUri: /api
/resource/{resourceId}:
  get:
    description: Get the content of a resource.
    headers:
      Accept:
        enum:
          - application/json
          - text/html
```
