### ISSUE TITLE
Optional properties in resource types not optional after being inherited 

### ISSUE THREAD

**Issue by abalmos** [mulesoft/api-console#47]
If a method is defined as optional in one resource type and then inherited by another resource type, with the 'type' keyword, that also defines the same method as optional, then that method appears to no longer be optional. The api-console displays all resources defined with the child type to have that method. Optional methods should stay optional if it is optional through out the entire list of inherited resource types. 

A minimal example:

``` yaml
#%RAML 0.8

---
title: 
resourceTypes:
  - common:
      get?:
  - base:
      type: common
      get?:
/files:
    type: base
```

Here /files will be shown to have a GET method when it should not.
