### ISSUE TITLE
Type section does not show type information

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#483]
For the following RAML

```yaml
#%RAML 1.0
title: Programming Language Populariy
version: 1
baseUri: http://example.com
types: 
  language:
    type: string
    description: A programming language name
    enum: [Ruby, Python, JavaScript]
```

The API console only renders

![image](https://user-images.githubusercontent.com/498114/27532371-08efad00-5a58-11e7-98d3-ba558ffca327.png)

As you can see, the type information like that this is a `string` and there is an enum defined is completely missing.
