### ISSUE TITLE
CSS rendering issues with the right panel menu

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#485]
The API console v4 does not correctly render the right panel menu with the following RAML

```yaml
#%RAML 0.8
title: Users API
version: 1
baseUri: https://{apiDomain}.someapi.com
/users:
  displayName: retrieve all users
  baseUriParameters:
    apiDomain:
      enum: [ "api" ]
  /{userId}/image:
    displayName: access users pictures
    baseUriParameters:
      apiDomain:
        enum: [ "static" ]
```

![image](https://user-images.githubusercontent.com/498114/27533242-ccdb9812-5a5a-11e7-8f97-338421b6c807.png)
