### ISSUE TITLE
Type informations are not rendered fully

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#486]
If a type has more meta information, they are not completely rendered in the description column. As far as I understand, this is not expected behaviour and should be a feature.

```yaml
#%RAML 0.8
title: Example API
version: v1
baseUri: https://{host}:{port}
baseUriParameters:
  host:
    displayName: Domain name / ip address
    type: string
    default: localhost
  port:
    displayName: Port
    type: integer
    default: 80
```

![image](https://user-images.githubusercontent.com/498114/27534626-9568159a-5a5f-11e7-9a67-012e06aa3662.png)

I would expect to see the default values and probably the display name as well.
