### ISSUE TITLE
Pattern input fields are not validated

### ISSUE THREAD

**Issue by sichvoge** [mulesoft/api-console#487]
Currently, v3 does validate pattern input fields inside the TryIt view

![image](https://user-images.githubusercontent.com/498114/27536425-03feb9c6-5a67-11e7-8237-93ff43cc55e2.png)

The new version v4 does not anymore. We should have that. 

RAML:

```yaml
#%RAML 0.8
title: test API
version: 1.0.0

traits:
  - sortable:
      queryParameters:
        sort:
          type: string
          example: authLevel,id:desc,metadata.title:asc
          pattern: ^\w(\.?[\w-]+)+(\:(desc|asc))?(\,\w(\.?[\w-]+)+(\:(desc|asc))?)*$
  - customizable:
      queryParameters:
        includes:
          type: string  
          example: id,signal,authLevel,metadata.title,videos
          pattern: ^\w(\.?[\w-]+)+(\,\w(\.?[\w-]+)+)*$
        excludes:
          type: string
          example: videos,dates
          pattern: ^[a-z](\.?[a-z-]+)+(\,[a-z](\.?[a-z-]+)+)*$

/movies:
  get:
    is: [sortable, customizable]
    queryParameters:
        another:
          type: string
          example: test
          pattern: ^[a-z]*$
```
