### ISSUE TITLE
broken field ordering in big objects

### ISSUE THREAD

**Issue by nektru** [mulesoft/api-console#493]
I makes raml like this:
```
#%RAML 1.0
title: Test field order

types:
  C:
    type: object
    properties:
      A: string
      B: string
      C: string
      D: string
      E: string
      F: string
      J: string
      K: string
      L: string
      M: string
```
api-console 4.0 displays fields in a mixed order:
```
{
  "L": "string",
  "M": "string",
  "A": "string",
  "F": "string",
  "D": "string",
  "B": "string",
  "J": "string",
  "C": "string",
  "E": "string",
  "K": "string"
}
```
This problem affects objects with a number of properties, greater than nine.
If remove one of this properties - order will be normal.
