### ISSUE TITLE
API console does not load raml file

### ISSUE THREAD

**Issue by philippebr01** [mulesoft/api-console#534]
Hi,
I'm trying to use api-console as described in the documentation

```html
<html>

<head>
    <link rel="import" href="bower_components/api-console/api-console.html">
</head>

<body>
    <api-console raml="api.raml"></api-console>
</body>

</html>
```

I'm using a simple raml just for test
```
#%RAML 1.0
title: console-api
version: v1

types: 
  Address: 
    type: object
    properties: 
      city: 
        type: string
        description: City name
      country: 
        type: string
        description: Country name
      state: 
        type: string
        description: State Abbreviation 
      street: 
        type: string
        description: Street info
      zip: 
        type: number
        description: Address zip code
  
  Phone:
    type: object
    properties: 
      number:
        type: string
        description: Client phone number
  Contact: 
    type: object
    properties: 
      email: 
        type: string
        description: Client e-mail
      phones:
        type: array
        items: Phone
        description: List with client phone numbers
  Client:
    type:  object
    properties: 
      identification:
        type: string
        description: Client identification
      name:
        type: string
        description: Client full name
      sex:
        enum: ["M","F"]
        description: Client sex
      birthdate:
        type: date-only
        description: Client birthdate
      contact:
        type: Contact
        description: Client contacts
      address:
        type: Address
        description: Client address
  Clients:
    type: Client[]
    
```

but the raml file is not loaded on the page, can you help me?

![captura de tela 2017-10-09 as 14 06 16](https://user-images.githubusercontent.com/10201985/31349804-2711baa8-acfb-11e7-9a8e-7ddf343106dc.png)
