### ISSUE TITLE
union types json not being re-rendered on variant selection

### ISSUE THREAD

**Issue by r3ticuli** [mulesoft/api-console#567]
here is a demo raml using a very simple union type.

```
#%RAML 1.0
title: Test API
types:
  typeA:
    type: typeB | typeC
  typeB:
    properties:
      number: integer
  typeC:
    properties:
      bool: boolean
/test:
  post:
    body:
      application/json:
        type: typeA
```

this is what api-console produces from this raml with type B (variant 1) selected : 

![image](https://user-images.githubusercontent.com/2349518/38636490-58200ae2-3d96-11e8-96f8-00847ff88c1a.png)

but when i switch to type C  (variant 2) . . . 

![image](https://user-images.githubusercontent.com/2349518/38636531-72b02400-3d96-11e8-85d4-7354c807acb7.png)

the json doesn't change, but the parameter and type below do. Seems like a bug, no?
