### ISSUE TITLE
Nesting resources in Version 5

### ISSUE THREAD

**Issue by mduesterhoeft** [mulesoft/api-console#571]
I was just looking at the `5.0.0-preview` version and really like it. One thing that would keep me from using it is that the resources are displayed all on the same level in the navigation:

In this [example](https://github.com/raml-org/raml-examples/blob/master/others/world-music-api/api.raml) there is a `/{songId}` resource nested under `/songs`

```yaml
/songs:
  displayName: Songs
  description:  Access to all songs inside the music world library.
  get:
    securedBy: [ oauth_2_0, null ]
    (monitoringInterval): 30
    queryParameters:
      genre:
        description: filter the songs by genre
  post:
  /{songId}:
    get:
```

![image](https://user-images.githubusercontent.com/13134480/41289874-74b92982-6e4b-11e8-8a83-2a6ce51059ef.png)

Especially for larger APIs this is really getting confusing.

Any plans to introduce the nesting of resources that was available in earlier versions?
