### ISSUE TITLE
Open API 3 No Response Information

### ISSUE THREAD

**Issue by dc950** [mulesoft/api-console#609]
When running the console from an AMF generated from any Open API 3 specification (e.g. [https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml)) then no types are present and there are no types shown for the responses.

This may be an issue with the AMF tooling as opposed to the api-console, but the AMF github page doesn't claim to support OAS 3 while this page does.

Other things I've noticed related to this:

When generating using the code provided [here](https://github.com/mulesoft/api-console/blob/master/docs/passing-api-data.md) (but adapting for OAS 3) the validation errors are not displayed as the `toString()` method causes an error:

```
TypeError: Cannot read property 'Vi' of undefined
    at Oea (...\node_modules\amf-client-js\amf.js:2803:91)
    at Po.d.Rn (...\node_modules\amf-client-js\amf.js:193:247)
    at Po.toString (...\node_modules\amf-client-js\amf.js:194:46)
    at amf.AMF.validate.then (...\<my-file>)
```

When using the api-console-cli to generate it, the following error appears several times but the amf file is still created (which still shows no response information):

```
- Source: http://a.ml/vocabularies/amf/parser#closed-shape
  Message: Property schema not supported in a OAS 3.0 parameter node
  Level: Violation
  Target: file://petstore.yaml#/web-api/end-points/%2Fpets/get/request/parameter/limit
  Property:
  Position: Some(LexicalInformation([(21,10)-(24,0)]))
  Location: file://petstore.yaml
```

I'm aware this issue should maybe be raised on the AMF github, but I am a bit confused and there is no information about OAS 3 there, and it is the instructions from here that led me to these problems.
