### ISSUE TITLE
uriParameter missing from html

### ISSUE THREAD

**Issue by marcadella** [mulesoft/api-console#610]
The uriParameters are ignored when generating html.

Here is an example:
```
#%RAML 1.0
title: Test
/users:
  description: Collection of user
  /{userId}:
    uriParameters:
      userId:
        displayName: userId
        description: User Id
```

In the generated html, there is nowhere I can see the description "User Id" and the endpoint list contains "/{userId}" instead of "userId" (the displayName). So it seems to me that the node "uriParameters" is ignored.

PS: By the way, why calling "endpoint" what is a "resource"??

**Comment by jarrodek** [comment]
It does look like the navigation and the request editor ignores display name for some reason. This is to be fixed.

As for resource vs endpoint. Endpoint is "a place" from which you can get a resource (if the endpoint actually returns a resource). Resource is a representation of something (like a model in a datastore) that a program can interact with using specific endpoint and operation (method). 
In REST API you have a list of endpoints which may return a resource. These are two different things and shouldn't be mixed.

**Comment by jarrodek** [comment]
I've analyzed what is happening here. It looks like the console works as intended.

The `dispayName` property added to the URI variable does not correspond to `displayName` of endpoint declaration. These are different things. If you would like the endpoint in the navigation to render different name than `/{userId}` you have to specify `displayName` there:

```yaml
#%RAML 1.0
title: Test
/users:
  description: Collection of user
  /{userId}:
    displayName: User Id
    uriParameters:
      userId:
        displayName: userId
        description: User Id
```

Closing as WAI.
