### ISSUE TITLE
Object description is not shown in array description

### ISSUE THREAD

**Issue by vkaderabek** [mulesoft/api-console#614]
I have RAML file contains something like:
```
#%RAML 1.0
title: Test Case
version: 1.0
mediaType: [ application/json ]

types:
  Obj1:
    type: object
    properties:
      item1:
        type: number
        description: item 1 description
      item2:
        type: integer
        minimum: 1
        required: false
        description: item 2 description
    description: Obj1 description

  Obj2:
    type: object
    properties:
      arrayAttribute:
        type: Obj1[]
        required: false
```

I expect that the description for array will be get from object from which is array composed.
As is shown here
<img width="730" alt="Snímek obrazovky 2019-08-05 v 14 16 19" src="https://user-images.githubusercontent.com/24653607/62465618-9cc6ee80-b78f-11e9-859a-e93c668be416.png">

It should be good if you want to use array of objects as attribute in multiple objects (it will not be necessary to copy description to each usage).
