### ISSUE TITLE
API console doesn't render headers from a trait when creating a new endpoint method in RAML extension fragment

### ISSUE THREAD

**Issue by deiteris** [mulesoft/api-console#689]
## Description
Given the following main RAML file:
```yaml
#%RAML 1.0
title: My API
mediaType: application/json
baseUri: https://production.com
protocols: [ HTTPS ]

/types:
  get:
```

I am trying to extend it with the following fragment:
```yaml
#%RAML 1.0 Extension
extends: api.raml # RAML API definition to extend

title: My Dev API # DEVELOPMENT-only API definition
baseUri: http://localhost # "localhost" baseUri
protocols: [ HTTP, HTTPS ] # allow unsecured HTTP

traits:
  customHeaders:
    headers:
      X-My-Custom-Header:

/types:
  get:
    is: [customHeaders]
  post:
    is: [customHeaders]
```

Both RAMLs parse without any errors, but when I open the extension fragment in the API console, `GET /types` has the headers inherited from the `customHeaders` trait and `POST /types` doesn't have the headers. Both endpoint methods show `Mixes in customHeaders.`.
![image](https://user-images.githubusercontent.com/6103913/118724687-93f5be80-b837-11eb-8d07-a407b3141b13.png)
![image](https://user-images.githubusercontent.com/6103913/118724705-99eb9f80-b837-11eb-8d6e-15a7942642cf.png)

But if I remove the GET method from the main RAML file and open the extension fragment, the headers appear correctly in both endpoint methods.

## Environment
- API Console 6.4.10
- AMF Parser 4.7.3

## Additional information

The extended header trait correctly appears in the `doc:extends` property of `apiContract:method`, so the issue is not in AMF parser.
