### ISSUE TITLE
Not able to "try it" on custom auth security schemas

### ISSUE THREAD

**Issue by danjenkins** [mulesoft/api-console#79]
After a while of figuring out that I can't use try it, if I'm using a custom security schema, I'm all ready to go and fork the project to implement the changes required - but then  I saw that there's a new version of console coming out soon? I see the features/console-2.0 branch too - should I be trying to add this functionality to the existing console or should I try out console v2? Does console v2 already have this functionality?

Thanks!

**Comment by jcenturion** [comment]
@danjenkins: The latest version have support for that. So, if you are using custom security schemes, now you will be able to see it listed under security ***scheme section***.

```yaml
securitySchemes:
  - custom_scheme_1:
      type: x-custom
      describedBy:
        headers:
          auth:
        queryParameters:
          access_token:
```

- The console will render:

![screen shot 2015-03-10 at 4 46 41 pm](https://cloud.githubusercontent.com/assets/302314/6587725/47785980-c745-11e4-85ef-3a7c0603b7c4.png)
