### ISSUE TITLE
Repeatable headers are rendered wrong

### ISSUE THREAD

**Issue by monami555** [mulesoft/api-console#81]
This is a minimal example of the problem. I have the following RAML file:

```
#%RAML 0.8
title: sample
baseUri: http://localhost/
version: v1
mediaType:  application/json

/pages:
  get:
    headers:
      link:
        repeat: true
        type: string
```

After I try to render it in a "Try it" tab, the "link" header is rendered with a little "plus" sign next to it, so that it can be multiplied, to provide multiple values. 

However, as soon as I add second header by pressing this "plus" sign, the second header gets the same value as the first header, and whichever input field I modify, the other gets modified as well. This makes the feature completely unusable.
